In [4]:
from datasets import load_dataset

ds = load_dataset("zeroshot/twitter-financial-news-sentiment")
ds

ImportError: cannot import name 'xopen' from 'datasets.utils.file_utils' (c:\Users\nasos\Desktop\CITY MSC\SEMESTER 2\NLP\NLP\.venv\Lib\site-packages\datasets\utils\file_utils.py)

In [19]:
import pandas as pd

splits = {'train': 'sent_train.csv', 'validation': 'sent_valid.csv'}
df_tr = pd.read_csv("hf://datasets/zeroshot/twitter-financial-news-sentiment/" + splits["train"])
df_val = pd.read_csv("hf://datasets/zeroshot/twitter-financial-news-sentiment/" + splits["validation"])
twitter_df = pd.concat([df_tr, df_val], ignore_index=True)

In [26]:
twitter_df

                                                    text  label
0      $BYND - JPMorgan reels in expectations on Beyo...      0
1      $CCL $RCL - Nomura points to bookings weakness...      0
2      $CX - Cemex cut at Credit Suisse, J.P. Morgan ...      0
3      $ESS: BTIG Research cuts to Neutral https://t....      0
4      $FNKO - Funko slides after Piper Jaffray PT cu...      0
...                                                  ...    ...
11926  Stocks making the biggest moves midday: TD Ame...      2
11927  Stocks making the biggest moves premarket: Fit...      2
11928  Stocks making the biggest moves premarket: Hom...      2
11929  Stocks making the biggest moves premarket: TD ...      2
11930         TCO, NNVC, GPOR and JE among midday movers      2

[11931 rows x 2 columns]

In [5]:
import pandas as pd
from datasets import concatenate_datasets

full_twitter = concatenate_datasets([ds["train"], ds["validation"]]).to_pandas()
full_twitter

ImportError: cannot import name 'xopen' from 'datasets.utils.file_utils' (c:\Users\nasos\Desktop\CITY MSC\SEMESTER 2\NLP\NLP\.venv\Lib\site-packages\datasets\utils\file_utils.py)

In [6]:
full_twitter['label'].value_counts()

NameError: name 'full_twitter' is not defined

In [7]:
import pandas as pd

phrasebank_df = pd.read_csv(
    'FinancialPhraseBank-v1.0/Sentences_75Agree.txt',
    sep='@',
    header=None,
    names=['text', 'sentiment'],
    encoding='latin-1'  # needed for special characters
)

phrasebank_df

                                                   text sentiment
0     According to Gran , the company has no plans t...   neutral
1     With the new production plant the company woul...  positive
2     For the last quarter of 2010 , Componenta 's n...  positive
3     In the third quarter of 2010 , net sales incre...  positive
4     Operating profit rose to EUR 13.1 mn from EUR ...  positive
...                                                 ...       ...
3448  Operating result for the 12-month period decre...  negative
3449  HELSINKI Thomson Financial - Shares in Cargote...  negative
3450  LONDON MarketWatch -- Share prices ended lower...  negative
3451  Operating profit fell to EUR 35.4 mn from EUR ...  negative
3452  Sales in Finland decreased by 10.5 % in Januar...  negative

[3453 rows x 2 columns]

In [8]:
phrasebank_df['sentiment'].value_counts()

sentiment
neutral     2146
positive     887
negative     420
Name: count, dtype: int64

In [9]:
label_map = {"neutral": 2, "positive": 1, "negative": 0}
phrasebank_df['sentiment'] = phrasebank_df['sentiment'].map(label_map)

phrasebank_df.rename(columns={"sentiment": "label"}, inplace=True)
phrasebank_df

                                                   text  label
0     According to Gran , the company has no plans t...      2
1     With the new production plant the company woul...      1
2     For the last quarter of 2010 , Componenta 's n...      1
3     In the third quarter of 2010 , net sales incre...      1
4     Operating profit rose to EUR 13.1 mn from EUR ...      1
...                                                 ...    ...
3448  Operating result for the 12-month period decre...      0
3449  HELSINKI Thomson Financial - Shares in Cargote...      0
3450  LONDON MarketWatch -- Share prices ended lower...      0
3451  Operating profit fell to EUR 35.4 mn from EUR ...      0
3452  Sales in Finland decreased by 10.5 % in Januar...      0

[3453 rows x 2 columns]

Tweets dataset already to integers:
0 -> bearish (negative)
1 -> bullish (positive)
2 -> neutral

In [10]:
phrasebank_df['label'].value_counts()

label
2    2146
1     887
0     420
Name: count, dtype: int64

In [11]:
full_twitter['label'].value_counts()

NameError: name 'full_twitter' is not defined

In [36]:
df_merged = pd.concat([phrasebank_df, full_twitter], ignore_index=True, sort=False)
df_merged

                                                    text  label
0      According to Gran , the company has no plans t...      2
1      With the new production plant the company woul...      1
2      For the last quarter of 2010 , Componenta 's n...      1
3      In the third quarter of 2010 , net sales incre...      1
4      Operating profit rose to EUR 13.1 mn from EUR ...      1
...                                                  ...    ...
15379  Stocks making the biggest moves midday: TD Ame...      2
15380  Stocks making the biggest moves premarket: Fit...      2
15381  Stocks making the biggest moves premarket: Hom...      2
15382  Stocks making the biggest moves premarket: TD ...      2
15383         TCO, NNVC, GPOR and JE among midday movers      2

[15384 rows x 2 columns]

In [37]:
df_merged['label'].value_counts()

label
2    9890
1    3285
0    2209
Name: count, dtype: int64